apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: module-freezer
  labels:
    app: module-freezer
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
