apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: module-freezer
  namespace: openshift-module-freezer
  labels:
    app: module-freezer
spec:
  selector:
    matchLabels:
      app: module-freezer
  template:
    metadata:
      labels:
        app: module-freezer
    spec:
      serviceAccountName: module-freezer
      hostPID: false
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: module-freezer
          image: quay.io/sdodsonrht/module-freezer:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POLL_INTERVAL
              value: "30"
            - name: REMOVE_TAINT_ON_RESOLVE
              value: "false"
            - name: LOCK_MODULES
              value: "true"
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: false
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          securityContext:
            privileged: true
            runAsUser: 0
      volumes:
        - name: proc
          hostPath:
            path: /proc
